@startuml Diagrama de Contexto

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS_2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define MATERIAL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/material

!include DEVICONS/angular.puml
!include DEVICONS/android.puml
!include DEVICONS_2/dotnetcore.puml

!include FONTAWESOME/users.puml
!include FONTAWESOME/user_tie.puml
!include FONTAWESOME/users_cog.puml
!include FONTAWESOME/viber.puml
!include FONTAWESOME/envelope_open_text.puml

!include MATERIAL/https.puml

Person(user, "Clientes", "Cliente que requiere soporte tecnico.", $sprite="users")
Person(adviser, "Asesores", "Personal que realiza la gestión del soporte técnico.", $sprite="user_tie")
Person(technical, "Técnicos", "Personal que realiza el soporte técnico informado.", $sprite="users_cog")

System_Boundary(app, "Apps") {
    Container(web_app, "Single-Page Application", "TypeScript, Angular, NodeJS", "Proporciona la funcionalidad para la gestión tanto a los clientes, asesores y tecnicos.", $sprite="angular")
    Container(mobile_app, "Mobile App", "C#, Xamarin Forms MVVM", "Proporciona la funcionalidad para la gestión tanto a los clientes, asesores y tecnicos.", $sprite="android")
}

Container(connect, "Call Center", "Amazon Connect", "Servicio como centro de contacto para las gestión de llamadas y contacto por chat y voz.", $sprite="img:./icons/AmazonConnect.png{scale=0.03}")

System_Boundary(auth, "Auth") {
    Container(identity, "Autenticación y Autorización", "Amazon API Gateway", "Administrar el acceso, mantenimiento, monitorie y proteccion a los recursos y servicios de manera segura.", $sprite="img:./icons/APIGateway.png{scale=0.1}")
    Container(lambda, "Lambda Auth", "AWS Lambda", "Autorizador de Lambda como caracteristica de API Gateway que utilizara función de Lambda para controlar el acceso a las API.", $sprite="img:./icons/AWSLambda.png{scale=0.05}")
}

Container(api, "API RESTful Application", "C#, NET Core 5.0, DDD", "Proporciona o maneja la funcionalidad para la logica del negocio a través de las API's JSON/HTTPS.", $sprite="dotnetcore")
Container(notification, "Sistema de Notificación", "Amazon Simple Notification Service", "Servicio de mensajería para la comunicación aplicación a aplicación (A2A) y aplicación a persona (A2P).", $sprite="img:./icons/AWSSNS.png{scale=0.05}")

Rel(user, web_app, "Usar", "https")
Rel(user, mobile_app, "Usar", "https")
Rel(adviser, web_app, "Usar", "https")
Rel(adviser, mobile_app, "Usar", "https")
Rel(technical, web_app, "Usar", "https")
Rel(technical, mobile_app, "Usar", "https")

Rel(web_app, identity, "Usar", "https")
Rel(mobile_app, identity, "Usar", "https")

Rel(user, connect, "Llamada y Chat")
Rel(connect, adviser, "Recepcion")

Rel(identity, lambda, "Token valido de acceso")
Rel(lambda, identity, "Politica de acceso")

Rel(identity, api, "Autentificación por token")

Rel_R(api, notification, "Usar")

Rel_R(notification, user, "Envio de SMS, push móvil y correo electrónico")
Rel_R(notification, technical, "Envio de SMS, push móvil y correo electrónico")

@enduml